-- MySQL Script generated by MySQL Workbench
-- Mon Sep 22 18:40:17 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema inder_e_sports
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inder_e_sports
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inder_e_sports` DEFAULT CHARACTER SET utf8 ;
USE `inder_e_sports` ;

-- -----------------------------------------------------
-- Table `inder_e_sports`.`COMUNA_BARRIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inder_e_sports`.`COMUNA_BARRIO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `COMUNA` VARCHAR(45) NOT NULL,
  `barrio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inder_e_sports`.`TIPO_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inder_e_sports`.`TIPO_USUARIO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inder_e_sports`.`PLATAFORMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inder_e_sports`.`PLATAFORMA` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inder_e_sports`.`JUEGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inder_e_sports`.`JUEGO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `clasificiacion_ESRB` VARCHAR(45) NULL,
  `estudio_dev` VARCHAR(45) NULL,
  `plataformas_disponibles` VARCHAR(45) NULL,
  `numero_jugadores` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `existencias_inventario` INT NULL,
  `PLATAFORMA_id` INT NOT NULL,
  PRIMARY KEY (`id`, `PLATAFORMA_id`),
  CONSTRAINT `fk_JUEGO_PLATAFORMA1`
    FOREIGN KEY (`PLATAFORMA_id`)
    REFERENCES `inder_e_sports`.`PLATAFORMA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inder_e_sports`.`EQUIPO_JUEGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inder_e_sports`.`EQUIPO_JUEGO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `horas` INT NOT NULL,
  `nivel` INT NOT NULL,
  `juego` VARCHAR(45) NULL,
  `JUEGO_id` INT NOT NULL,
  PRIMARY KEY (`id`, `JUEGO_id`),
  CONSTRAINT `fk_EQUIPO_JUEGO_JUEGO1`
    FOREIGN KEY (`JUEGO_id`)
    REFERENCES `inder_e_sports`.`JUEGO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inder_e_sports`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inder_e_sports`.`USUARIO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_documento` VARCHAR(45) NOT NULL,
  `numero_documento` VARCHAR(45) NOT NULL,
  `primer_nombre` VARCHAR(45) NOT NULL,
  `segundo_nombre` VARCHAR(45) NULL,
  `primer_apellido` VARCHAR(45) NOT NULL,
  `segundo_apellido` VARCHAR(45) NULL,
  `fecha_nacimiento` DATETIME NOT NULL,
  `sexo` VARCHAR(45) NULL,
  `direccion_domicilio` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(45) NULL,
  `clave` VARCHAR(45) NULL,
  `acudiente` INT NULL,
  `COMUNA_BARRIO_id` INT NOT NULL,
  `TIPO_USUARIO_id` INT NOT NULL,
  `EQUIPO_JUEGO_id` INT NOT NULL,
  PRIMARY KEY (`id`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIO_COMUNA_BARRIO1`
    FOREIGN KEY (`COMUNA_BARRIO_id`)
    REFERENCES `inder_e_sports`.`COMUNA_BARRIO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIO_TIPO_USUARIO1`
    FOREIGN KEY (`TIPO_USUARIO_id`)
    REFERENCES `inder_e_sports`.`TIPO_USUARIO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIO_EQUIPO_JUEGO1`
    FOREIGN KEY (`EQUIPO_JUEGO_id`)
    REFERENCES `inder_e_sports`.`EQUIPO_JUEGO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inder_e_sports`.`TELEFONO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inder_e_sports`.`TELEFONO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `USUARIO_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_TELEFONO_USUARIO`
    FOREIGN KEY (`USUARIO_id`)
    REFERENCES `inder_e_sports`.`USUARIO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inder_e_sports`.`LOGRO_TROFEO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inder_e_sports`.`LOGRO_TROFEO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `puntos_req` INT NOT NULL,
  `JUEGO_id` INT NOT NULL,
  PRIMARY KEY (`id`, `JUEGO_id`),
  CONSTRAINT `fk_LOGRO_TROFEO_JUEGO1`
    FOREIGN KEY (`JUEGO_id`)
    REFERENCES `inder_e_sports`.`JUEGO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inder_e_sports`.`CONSOLA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inder_e_sports`.`CONSOLA` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `numero_serie` VARCHAR(45) NOT NULL,
  `existencia_inventario` INT NOT NULL,
  `dir_ip` VARCHAR(45) NULL,
  `dir_mac` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inder_e_sports`.`CONTROL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inder_e_sports`.`CONTROL` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero_serie` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `CONSOLA_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_CONTROL_CONSOLA1`
    FOREIGN KEY (`CONSOLA_id`)
    REFERENCES `inder_e_sports`.`CONSOLA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inder_e_sports`.`SESION_ENTRENAMIENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inder_e_sports`.`SESION_ENTRENAMIENTO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_agenda` DATETIME NOT NULL,
  `hora_ini` DATETIME NULL,
  `hora_fin` DATETIME NULL,
  `JUEGO_id` INT NOT NULL,
  `arbitro` INT NOT NULL,
  PRIMARY KEY (`id`, `JUEGO_id`, `arbitro`),
  CONSTRAINT `fk_SESION_ENTRENAMIENTO_JUEGO1`
    FOREIGN KEY (`JUEGO_id`)
    REFERENCES `inder_e_sports`.`JUEGO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SESION_ENTRENAMIENTO_USUARIO1`
    FOREIGN KEY (`arbitro`)
    REFERENCES `inder_e_sports`.`USUARIO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- Inserts for COMUNA_BARRIO
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Popular', 'Santo Domingo Savio');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Popular', 'Popular 1');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Popular', 'Granizal');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Santa Cruz', 'Santa Cruz');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Santa Cruz', 'La Rosa');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Santa Cruz', 'Moscú No. 1');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Manrique', 'Manrique Central');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Manrique', 'Las Granjas');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Manrique', 'Campo Valdés');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Aranjuez', 'Aranjuez');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Aranjuez', 'Berlin');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Aranjuez', 'San Isidro');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Castilla', 'Castilla');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Castilla', 'Pedregal');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Castilla', 'Doce de Octubre');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Doce de Octubre', 'Santander');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Doce de Octubre', 'Picacho');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Robledo', 'Robledo');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Robledo', 'El Volador');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Robledo', 'San German');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Villa Hermosa', 'Villa Hermosa');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Villa Hermosa', 'La Mansión');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Buenos Aires', 'Buenos Aires');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Buenos Aires', 'Caicedo');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('La Candelaria', 'Prado');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('La Candelaria', 'Boston');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('La Candelaria', 'San Benito');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Laureles-Estadio', 'Laureles');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Laureles-Estadio', 'Estadio');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Laureles-Estadio', 'San Joaquin');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('La América', 'La América');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('La América', 'Calasanz');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('San Javier', 'San Javier');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('San Javier', 'El Socorro');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('El Poblado', 'El Poblado');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('El Poblado', 'Manila');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('El Poblado', 'Astorga');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Guayabal', 'Guayabal');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Guayabal', 'Trinidad');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Belén', 'Belén');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Belén', 'Rosales');
INSERT INTO `inder_e_sports`.`COMUNA_BARRIO` (`COMUNA`, `barrio`) VALUES ('Belén', 'Fatima');

-- Inserts for TIPO_USUARIO
INSERT INTO `inder_e_sports`.`TIPO_USUARIO` (`nombre`, `descripcion`) VALUES ('Jugador', 'Participante de torneos');
INSERT INTO `inder_e_sports`.`TIPO_USUARIO` (`nombre`, `descripcion`) VALUES ('Arbitro', 'Juez de partidas');
INSERT INTO `inder_e_sports`.`TIPO_USUARIO` (`nombre`, `descripcion`) VALUES ('Admin', 'Administrador del sistema');
INSERT INTO `inder_e_sports`.`TIPO_USUARIO` (`nombre`, `descripcion`) VALUES ('Espectador', 'Usuario visualizador');
INSERT INTO `inder_e_sports`.`TIPO_USUARIO` (`nombre`, `descripcion`) VALUES ('Entrenador', 'Entrenador de equipos');

-- Inserts for PLATAFORMA
INSERT INTO `inder_e_sports`.`PLATAFORMA` (`nombre`, `marca`) VALUES ('PC', 'Microsoft Windows');
INSERT INTO `inder_e_sports`.`PLATAFORMA` (`nombre`, `marca`) VALUES ('PlayStation 4', 'Sony');
INSERT INTO `inder_e_sports`.`PLATAFORMA` (`nombre`, `marca`) VALUES ('PlayStation 5', 'Sony');
INSERT INTO `inder_e_sports`.`PLATAFORMA` (`nombre`, `marca`) VALUES ('Xbox One', 'Microsoft');
INSERT INTO `inder_e_sports`.`PLATAFORMA` (`nombre`, `marca`) VALUES ('Xbox Series X', 'Microsoft');
INSERT INTO `inder_e_sports`.`PLATAFORMA` (`nombre`, `marca`) VALUES ('Nintendo Switch', 'Nintendo');
INSERT INTO `inder_e_sports`.`PLATAFORMA` (`nombre`, `marca`) VALUES ('Mobile Android', 'Google');
INSERT INTO `inder_e_sports`.`PLATAFORMA` (`nombre`, `marca`) VALUES ('Mobile iOS', 'Apple');
INSERT INTO `inder_e_sports`.`PLATAFORMA` (`nombre`, `marca`) VALUES ('PC', 'Linux');
INSERT INTO `inder_e_sports`.`PLATAFORMA` (`nombre`, `marca`) VALUES ('PC', 'Mac');

-- Inserts for JUEGO
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('League of Legends', 'T', 'Riot Games', 'PC', '5v5', 'MOBA', 19, 1);
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('Valorant', 'T', 'Riot Games', 'PC', '5v5', 'Shooter', 19, 2);
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('FIFA 24', 'E', 'EA Sports', 'Multi', '1v1', 'Deportes', 18, 3);
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('Call of Duty', 'M', 'Activision', 'Multi', 'Multi', 'Shooter', 16, 4);
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('Fortnite', 'T', 'Epic Games', 'Multi', '100', 'Battle Royale', 11, 5);
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('Minecraft', 'E', 'Mojang', 'Multi', 'Multi', 'Sandbox', 17, 6);
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('Overwatch 2', 'T', 'Blizzard', 'Multi', '5v5', 'Shooter', 12, 7);
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('CS:GO 2', 'M', 'Valve', 'PC', '5v5', 'Shooter', 5, 8);
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('Dota 2', 'T', 'Valve', 'PC', '5v5', 'MOBA', 19, 9);
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('Rocket League', 'E', 'Psyonix', 'Multi', '3v3', 'Deportes', 5, 10);
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('Street Fighter 6', 'T', 'Capcom', 'Multi', '1v1', 'Lucha', 13, 1);
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('Tekken 8', 'T', 'Bandai Namco', 'Multi', '1v1', 'Lucha', 4, 2);
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('Super Smash Bros', 'E', 'Nintendo', 'Switch', '1v1', 'Lucha', 10, 3);
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('Mario Kart 8', 'E', 'Nintendo', 'Switch', 'Multi', 'Carreras', 9, 4);
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('Apex Legends', 'T', 'Respawn', 'Multi', '60', 'Battle Royale', 8, 5);
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('PUBG', 'M', 'Krafton', 'Multi', '100', 'Battle Royale', 11, 6);
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('Rainbow Six Siege', 'M', 'Ubisoft', 'Multi', '5v5', 'Shooter', 13, 7);
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('Among Us', 'E', 'Innersloth', 'Multi', '10', 'Social', 16, 8);
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('Fall Guys', 'E', 'Mediatonic', 'Multi', '60', 'Platformer', 16, 9);
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('Genshin Impact', 'T', 'HoYoverse', 'Multi', '1', 'RPG', 1, 10);
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('Clash Royale', 'E', 'Supercell', 'Mobile', '1v1', 'Estrategia', 7, 1);
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('Free Fire', 'M', 'Garena', 'Mobile', '50', 'Battle Royale', 1, 2);
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('Brawl Stars', 'E', 'Supercell', 'Mobile', '3v3', 'Accion', 16, 3);
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('Pokemon Unite', 'E', 'Pokemon Co', 'Multi', '5v5', 'MOBA', 20, 4);
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('Halo Infinite', 'M', '343 Ind', 'Xbox/PC', '4v4', 'Shooter', 3, 5);
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('Forza Horizon 5', 'E', 'Playground', 'Xbox/PC', 'Multi', 'Carreras', 3, 6);
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('Gran Turismo 7', 'E', 'Polyphony', 'PS', 'Multi', 'Carreras', 8, 7);
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('Mortal Kombat 1', 'M', 'NetherRealm', 'Multi', '1v1', 'Lucha', 16, 8);
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('Diablo IV', 'M', 'Blizzard', 'Multi', 'Multi', 'RPG', 17, 9);
INSERT INTO `inder_e_sports`.`JUEGO` (`nombre`, `clasificiacion_ESRB`, `estudio_dev`, `plataformas_disponibles`, `numero_jugadores`, `tipo`, `existencias_inventario`, `PLATAFORMA_id`) VALUES ('StarCraft II', 'T', 'Blizzard', 'PC', '1v1', 'RTS', 10, 10);

-- Inserts for EQUIPO_JUEGO
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 1', 590, 25, 'Juego 2', 2);
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 2', 805, 46, 'Juego 3', 3);
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 3', 25, 1, 'Juego 4', 4);
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 4', 537, 30, 'Juego 5', 5);
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 5', 583, 29, 'Juego 6', 6);
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 6', 480, 45, 'Juego 7', 7);
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 7', 106, 91, 'Juego 8', 8);
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 8', 942, 32, 'Juego 9', 9);
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 9', 393, 96, 'Juego 10', 10);
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 10', 218, 18, 'Juego 11', 11);
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 11', 32, 43, 'Juego 12', 12);
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 12', 652, 61, 'Juego 13', 13);
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 13', 985, 31, 'Juego 14', 14);
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 14', 814, 26, 'Juego 15', 15);
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 15', 918, 60, 'Juego 16', 16);
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 16', 293, 72, 'Juego 17', 17);
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 17', 436, 38, 'Juego 18', 18);
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 18', 386, 36, 'Juego 19', 19);
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 19', 121, 81, 'Juego 20', 20);
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 20', 578, 94, 'Juego 21', 21);
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 21', 966, 91, 'Juego 22', 22);
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 22', 672, 89, 'Juego 23', 23);
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 23', 399, 57, 'Juego 24', 24);
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 24', 606, 33, 'Juego 25', 25);
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 25', 711, 35, 'Juego 26', 26);
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 26', 471, 25, 'Juego 27', 27);
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 27', 831, 79, 'Juego 28', 28);
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 28', 807, 82, 'Juego 29', 29);
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 29', 110, 36, 'Juego 30', 30);
INSERT INTO `inder_e_sports`.`EQUIPO_JUEGO` (`nombre`, `horas`, `nivel`, `juego`, `JUEGO_id`) VALUES ('Equipo 30', 298, 60, 'Juego 1', 1);

-- Inserts for USUARIO
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000001', 'Pedro', 'Ramirez', '2000-01-01', 'Calle 1 # 1-1', 'User1', 'pass1', 2, 2, 2);
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000002', 'Pedro', 'Castro', '2000-01-01', 'Calle 2 # 2-2', 'User2', 'pass2', 3, 3, 3);
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000003', 'Felipe', 'Castro', '2000-01-01', 'Calle 3 # 3-3', 'User3', 'pass3', 4, 4, 4);
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000004', 'Daniel', 'Rodriguez', '2000-01-01', 'Calle 4 # 4-4', 'User4', 'pass4', 5, 5, 5);
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000005', 'Jose', 'Castro', '2000-01-01', 'Calle 5 # 5-5', 'User5', 'pass5', 6, 1, 6);
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000006', 'Laura', 'Ruiz', '2000-01-01', 'Calle 6 # 6-6', 'User6', 'pass6', 7, 2, 7);
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000007', 'David', 'Garcia', '2000-01-01', 'Calle 7 # 7-7', 'User7', 'pass7', 8, 3, 8);
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000008', 'Camila', 'Flores', '2000-01-01', 'Calle 8 # 8-8', 'User8', 'pass8', 9, 4, 9);
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000009', 'Andres', 'Rivera', '2000-01-01', 'Calle 9 # 9-9', 'User9', 'pass9', 10, 5, 10);
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000010', 'Gabriel', 'Gonzalez', '2000-01-01', 'Calle 10 # 10-10', 'User10', 'pass10', 11, 1, 11);
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000011', 'Camila', 'Martinez', '2000-01-01', 'Calle 11 # 11-11', 'User11', 'pass11', 12, 2, 12);
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000012', 'Alejandro', 'Alvarez', '2000-01-01', 'Calle 12 # 12-12', 'User12', 'pass12', 13, 3, 13);
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000013', 'Diego', 'Hernandez', '2000-01-01', 'Calle 13 # 13-13', 'User13', 'pass13', 14, 4, 14);
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000014', 'Ana', 'Hernandez', '2000-01-01', 'Calle 14 # 14-14', 'User14', 'pass14', 15, 5, 15);
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000015', 'David', 'Ruiz', '2000-01-01', 'Calle 15 # 15-15', 'User15', 'pass15', 16, 1, 16);
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000016', 'Ana', 'Lopez', '2000-01-01', 'Calle 16 # 16-16', 'User16', 'pass16', 17, 2, 17);
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000017', 'Juan', 'Castro', '2000-01-01', 'Calle 17 # 17-17', 'User17', 'pass17', 18, 3, 18);
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000018', 'Juan', 'Rivera', '2000-01-01', 'Calle 18 # 18-18', 'User18', 'pass18', 19, 4, 19);
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000019', 'Felipe', 'Lopez', '2000-01-01', 'Calle 19 # 19-19', 'User19', 'pass19', 20, 5, 20);
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000020', 'Sofia', 'Lopez', '2000-01-01', 'Calle 20 # 20-20', 'User20', 'pass20', 21, 1, 21);
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000021', 'Valentina', 'Rivera', '2000-01-01', 'Calle 21 # 21-21', 'User21', 'pass21', 22, 2, 22);
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000022', 'Juan', 'Moreno', '2000-01-01', 'Calle 22 # 22-22', 'User22', 'pass22', 23, 3, 23);
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000023', 'Pedro', 'Lopez', '2000-01-01', 'Calle 23 # 23-23', 'User23', 'pass23', 24, 4, 24);
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000024', 'Andres', 'Torres', '2000-01-01', 'Calle 24 # 24-24', 'User24', 'pass24', 25, 5, 25);
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000025', 'Felipe', 'Rivera', '2000-01-01', 'Calle 25 # 25-25', 'User25', 'pass25', 26, 1, 26);
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000026', 'Jose', 'Diaz', '2000-01-01', 'Calle 26 # 26-26', 'User26', 'pass26', 27, 2, 27);
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000027', 'Camila', 'Lopez', '2000-01-01', 'Calle 27 # 27-27', 'User27', 'pass27', 28, 3, 28);
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000028', 'Ana', 'Ramirez', '2000-01-01', 'Calle 28 # 28-28', 'User28', 'pass28', 29, 4, 29);
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000029', 'Ana', 'Torres', '2000-01-01', 'Calle 29 # 29-29', 'User29', 'pass29', 30, 5, 30);
INSERT INTO `inder_e_sports`.`USUARIO` (`tipo_documento`, `numero_documento`, `primer_nombre`, `primer_apellido`, `fecha_nacimiento`, `direccion_domicilio`, `nickname`, `clave`, `COMUNA_BARRIO_id`, `TIPO_USUARIO_id`, `EQUIPO_JUEGO_id`) VALUES ('CC', '1000030', 'Jose', 'Garcia', '2000-01-01', 'Calle 30 # 30-30', 'User30', 'pass30', 31, 1, 1);

-- Inserts for TELEFONO
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000001', 'Movil', 1);
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000002', 'Movil', 2);
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000003', 'Movil', 3);
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000004', 'Movil', 4);
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000005', 'Movil', 5);
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000006', 'Movil', 6);
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000007', 'Movil', 7);
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000008', 'Movil', 8);
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000009', 'Movil', 9);
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000010', 'Movil', 10);
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000011', 'Movil', 11);
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000012', 'Movil', 12);
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000013', 'Movil', 13);
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000014', 'Movil', 14);
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000015', 'Movil', 15);
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000016', 'Movil', 16);
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000017', 'Movil', 17);
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000018', 'Movil', 18);
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000019', 'Movil', 19);
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000020', 'Movil', 20);
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000021', 'Movil', 21);
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000022', 'Movil', 22);
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000023', 'Movil', 23);
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000024', 'Movil', 24);
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000025', 'Movil', 25);
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000026', 'Movil', 26);
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000027', 'Movil', 27);
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000028', 'Movil', 28);
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000029', 'Movil', 29);
INSERT INTO `inder_e_sports`.`TELEFONO` (`numero`, `tipo`, `USUARIO_id`) VALUES ('3001000030', 'Movil', 30);

-- Inserts for LOGRO_TROFEO
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 1', 4448, 2);
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 2', 2704, 3);
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 3', 647, 4);
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 4', 695, 5);
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 5', 2857, 6);
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 6', 1217, 7);
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 7', 2699, 8);
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 8', 2977, 9);
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 9', 328, 10);
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 10', 3652, 11);
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 11', 2466, 12);
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 12', 4913, 13);
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 13', 3922, 14);
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 14', 834, 15);
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 15', 4216, 16);
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 16', 4855, 17);
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 17', 1840, 18);
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 18', 1423, 19);
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 19', 3483, 20);
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 20', 2570, 21);
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 21', 1598, 22);
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 22', 4205, 23);
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 23', 1808, 24);
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 24', 3670, 25);
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 25', 2613, 26);
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 26', 2505, 27);
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 27', 4062, 28);
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 28', 2923, 29);
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 29', 1199, 30);
INSERT INTO `inder_e_sports`.`LOGRO_TROFEO` (`nombre`, `puntos_req`, `JUEGO_id`) VALUES ('Logro 30', 719, 1);

-- Inserts for CONSOLA
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 1', 'SN1001', 1, '192.168.1.1', 'AA:BB:CC:DD:EE:01');
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 2', 'SN1002', 1, '192.168.1.2', 'AA:BB:CC:DD:EE:02');
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 3', 'SN1003', 1, '192.168.1.3', 'AA:BB:CC:DD:EE:03');
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 4', 'SN1004', 1, '192.168.1.4', 'AA:BB:CC:DD:EE:04');
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 5', 'SN1005', 1, '192.168.1.5', 'AA:BB:CC:DD:EE:05');
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 6', 'SN1006', 1, '192.168.1.6', 'AA:BB:CC:DD:EE:06');
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 7', 'SN1007', 1, '192.168.1.7', 'AA:BB:CC:DD:EE:07');
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 8', 'SN1008', 1, '192.168.1.8', 'AA:BB:CC:DD:EE:08');
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 9', 'SN1009', 1, '192.168.1.9', 'AA:BB:CC:DD:EE:09');
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 10', 'SN1010', 1, '192.168.1.10', 'AA:BB:CC:DD:EE:0a');
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 11', 'SN1011', 1, '192.168.1.11', 'AA:BB:CC:DD:EE:0b');
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 12', 'SN1012', 1, '192.168.1.12', 'AA:BB:CC:DD:EE:0c');
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 13', 'SN1013', 1, '192.168.1.13', 'AA:BB:CC:DD:EE:0d');
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 14', 'SN1014', 1, '192.168.1.14', 'AA:BB:CC:DD:EE:0e');
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 15', 'SN1015', 1, '192.168.1.15', 'AA:BB:CC:DD:EE:0f');
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 16', 'SN1016', 1, '192.168.1.16', 'AA:BB:CC:DD:EE:10');
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 17', 'SN1017', 1, '192.168.1.17', 'AA:BB:CC:DD:EE:11');
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 18', 'SN1018', 1, '192.168.1.18', 'AA:BB:CC:DD:EE:12');
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 19', 'SN1019', 1, '192.168.1.19', 'AA:BB:CC:DD:EE:13');
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 20', 'SN1020', 1, '192.168.1.20', 'AA:BB:CC:DD:EE:14');
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 21', 'SN1021', 1, '192.168.1.21', 'AA:BB:CC:DD:EE:15');
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 22', 'SN1022', 1, '192.168.1.22', 'AA:BB:CC:DD:EE:16');
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 23', 'SN1023', 1, '192.168.1.23', 'AA:BB:CC:DD:EE:17');
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 24', 'SN1024', 1, '192.168.1.24', 'AA:BB:CC:DD:EE:18');
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 25', 'SN1025', 1, '192.168.1.25', 'AA:BB:CC:DD:EE:19');
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 26', 'SN1026', 1, '192.168.1.26', 'AA:BB:CC:DD:EE:1a');
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 27', 'SN1027', 1, '192.168.1.27', 'AA:BB:CC:DD:EE:1b');
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 28', 'SN1028', 1, '192.168.1.28', 'AA:BB:CC:DD:EE:1c');
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 29', 'SN1029', 1, '192.168.1.29', 'AA:BB:CC:DD:EE:1d');
INSERT INTO `inder_e_sports`.`CONSOLA` (`nombre`, `numero_serie`, `existencia_inventario`, `dir_ip`, `dir_mac`) VALUES ('Consola 30', 'SN1030', 1, '192.168.1.30', 'AA:BB:CC:DD:EE:1e');

-- Inserts for CONTROL
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1001', 'Inalambrico', 2);
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1002', 'Inalambrico', 3);
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1003', 'Inalambrico', 4);
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1004', 'Inalambrico', 5);
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1005', 'Inalambrico', 6);
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1006', 'Inalambrico', 7);
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1007', 'Inalambrico', 8);
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1008', 'Inalambrico', 9);
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1009', 'Inalambrico', 10);
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1010', 'Inalambrico', 11);
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1011', 'Inalambrico', 12);
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1012', 'Inalambrico', 13);
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1013', 'Inalambrico', 14);
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1014', 'Inalambrico', 15);
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1015', 'Inalambrico', 16);
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1016', 'Inalambrico', 17);
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1017', 'Inalambrico', 18);
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1018', 'Inalambrico', 19);
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1019', 'Inalambrico', 20);
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1020', 'Inalambrico', 21);
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1021', 'Inalambrico', 22);
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1022', 'Inalambrico', 23);
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1023', 'Inalambrico', 24);
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1024', 'Inalambrico', 25);
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1025', 'Inalambrico', 26);
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1026', 'Inalambrico', 27);
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1027', 'Inalambrico', 28);
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1028', 'Inalambrico', 29);
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1029', 'Inalambrico', 30);
INSERT INTO `inder_e_sports`.`CONTROL` (`numero_serie`, `tipo`, `CONSOLA_id`) VALUES ('CTRL1030', 'Inalambrico', 1);

-- Inserts for SESION_ENTRENAMIENTO
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-01 10:00:00', '2025-10-01 10:00:00', '2025-10-01 12:00:00', 2, 2);
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-02 10:00:00', '2025-10-02 10:00:00', '2025-10-02 12:00:00', 3, 3);
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-03 10:00:00', '2025-10-03 10:00:00', '2025-10-03 12:00:00', 4, 4);
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-04 10:00:00', '2025-10-04 10:00:00', '2025-10-04 12:00:00', 5, 5);
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-05 10:00:00', '2025-10-05 10:00:00', '2025-10-05 12:00:00', 6, 6);
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-06 10:00:00', '2025-10-06 10:00:00', '2025-10-06 12:00:00', 7, 7);
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-07 10:00:00', '2025-10-07 10:00:00', '2025-10-07 12:00:00', 8, 8);
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-08 10:00:00', '2025-10-08 10:00:00', '2025-10-08 12:00:00', 9, 9);
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-09 10:00:00', '2025-10-09 10:00:00', '2025-10-09 12:00:00', 10, 10);
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-10 10:00:00', '2025-10-10 10:00:00', '2025-10-10 12:00:00', 11, 11);
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-11 10:00:00', '2025-10-11 10:00:00', '2025-10-11 12:00:00', 12, 12);
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-12 10:00:00', '2025-10-12 10:00:00', '2025-10-12 12:00:00', 13, 13);
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-13 10:00:00', '2025-10-13 10:00:00', '2025-10-13 12:00:00', 14, 14);
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-14 10:00:00', '2025-10-14 10:00:00', '2025-10-14 12:00:00', 15, 15);
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-15 10:00:00', '2025-10-15 10:00:00', '2025-10-15 12:00:00', 16, 16);
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-16 10:00:00', '2025-10-16 10:00:00', '2025-10-16 12:00:00', 17, 17);
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-17 10:00:00', '2025-10-17 10:00:00', '2025-10-17 12:00:00', 18, 18);
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-18 10:00:00', '2025-10-18 10:00:00', '2025-10-18 12:00:00', 19, 19);
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-19 10:00:00', '2025-10-19 10:00:00', '2025-10-19 12:00:00', 20, 20);
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-20 10:00:00', '2025-10-20 10:00:00', '2025-10-20 12:00:00', 21, 21);
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-21 10:00:00', '2025-10-21 10:00:00', '2025-10-21 12:00:00', 22, 22);
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-22 10:00:00', '2025-10-22 10:00:00', '2025-10-22 12:00:00', 23, 23);
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-23 10:00:00', '2025-10-23 10:00:00', '2025-10-23 12:00:00', 24, 24);
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-24 10:00:00', '2025-10-24 10:00:00', '2025-10-24 12:00:00', 25, 25);
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-25 10:00:00', '2025-10-25 10:00:00', '2025-10-25 12:00:00', 26, 26);
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-26 10:00:00', '2025-10-26 10:00:00', '2025-10-26 12:00:00', 27, 27);
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-27 10:00:00', '2025-10-27 10:00:00', '2025-10-27 12:00:00', 28, 28);
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-28 10:00:00', '2025-10-28 10:00:00', '2025-10-28 12:00:00', 29, 29);
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-29 10:00:00', '2025-10-29 10:00:00', '2025-10-29 12:00:00', 30, 30);
INSERT INTO `inder_e_sports`.`SESION_ENTRENAMIENTO` (`fecha_agenda`, `hora_ini`, `hora_fin`, `JUEGO_id`, `arbitro`) VALUES ('2025-10-30 10:00:00', '2025-10-30 10:00:00', '2025-10-30 12:00:00', 1, 1);

